package jSyn.lib.filter;
public enum FilterType {
	ONE_ZERO, ONE_POLE, ONE_POLE_ONE_ZERO, TWO_POLES, TWO_POLES_TWO_ZEROS, BAND_PASS, BAND_STOP, HIGH_PASS, HIGH_SELF, LOW_PASS, LOW_SHELF, STATE_VARIABLE, LATCH, SCHMIDT_TRIGGER
}